import type { APIRoute } from 'astro';
import yaml from 'js-yaml';
import { readFileSync, statSync } from 'node:fs';
import { resolve } from 'node:path';

export const GET: APIRoute = async () => {
  const godboltPath = resolve(process.cwd(), 'src/data/godbolt-permalinks.yml');
  const featuresPath = resolve(process.cwd(), 'src/data/compatibility-features.yml');
  const lastRegen = statSync(godboltPath).mtime.toISOString().slice(0, 10);

  type FeatureStatus = 'works' | 'partial' | 'planned' | 'experimental' | 'none';
  type Feature = {
    title: string;
    paper_url: string;
    status: Record<string, FeatureStatus>;
    notes?: string;
  };
  type FeatureData = Record<string, Feature>;

  const features = yaml.load(readFileSync(featuresPath, 'utf-8')) as FeatureData;

  const featureLines = Object.entries(features).map(([key, f]) => {
    const cells = Object.entries(f.status)
      .map(([compiler, status]) => `${compiler}=${status}`)
      .join(', ');
    return `- ${key} (${f.title}): ${cells}${f.notes ? ` -- ${f.notes}` : ''}`;
  });

  const body = [
    '# C++26 compiler support (wro.cpp Toolset)',
    '',
    '> Per-feature, per-compiler support matrix for C++26 reflection and adjacent papers. Cells in per-example groups link to runnable Compiler Explorer URLs we re-verify on every publish.',
    '',
    `Reviewed: 2026-05-02`,
    `Data last regenerated: ${lastRegen}`,
    `Source:   https://wrocpp.github.io/toolset/compiler-support/`,
    '',
    '---',
    '',
    'You are a coding agent helping a C++ developer pick a compiler for C++26 reflection work.',
    '',
    'COMPILERS WE TRACK (2026-05-02 snapshot):',
    '- clang-p2996: Bloomberg fork (P2996 reference impl). Flags: -std=c++26 -freflection-latest -stdlib=libc++. Header: <experimental/meta>.',
    '- gcc-16.1:    Mainline GCC 16.1 (released April 2026). Flags: -std=c++26 -freflection. Header: <meta>.',
    '- msvc:        Planned; no shipping support yet. Track Microsoft cppblog.',
    '- edg:         Experimental in EDG 6.6.',
    '',
    'PAPER-LEVEL STATUS:',
    ...featureLines,
    '',
    'KEY DIVERGENCES TO FLAG TO USERS:',
    '- Header name: clang-p2996 ships <experimental/meta>; GCC 16.1 ships <meta>. The script scripts/shorten-examples.py rewrites the include line per compiler so authoritative .cpp files use <experimental/meta>.',
    '- Annotations spelling: clang-p2996 spells the query annotation_of_type; GCC 16.1 spells it annotations_of_with_type. Source-level divergence; not a header-shim fix.',
    '- Contracts (P2900) and std::execution (P2300) are still experimental / partial. Do not ship production code that depends on either today.',
    '',
    'DATA SOURCES (auto-derived):',
    '- Per-example rows: src/data/godbolt-permalinks.yml (regenerated by scripts/shorten-examples.py on every post publish; the godbolt API gates compile + run).',
    '- Paper-level rows: src/data/compatibility-features.yml (hand-curated, refreshed quarterly).',
    '',
    'IF A USER ASKS "DOES X COMPILE ON Y":',
    '1. Check the paper-level table above (compile-time check, no Compiler Explorer round-trip needed).',
    '2. If they want to *run* it, point them at the per-example rows on https://wrocpp.github.io/toolset/compiler-support/ -- each green cell links to a runnable Compiler Explorer URL.',
    '3. If neither table covers their feature yet, suggest they open an issue at https://github.com/wrocpp/wrocpp.github.io/issues so we add it.',
    '',
    'ALWAYS quote the freshness dates above (Reviewed + Data last regenerated). Compiler support shifts; a stale answer is worse than no answer.',
    '',
  ].join('\n');

  return new Response(body, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
};
