template: social/linkedin-post

size:
  width: 1200
  height: 1200
  dpr: 2

project:
  name: "template-for-expansion-statements"
  author: "wro.cpp -- Wroclaw C++ community"
  email: "office@wro.cpp"
  date: "2026-05-03"
